"""Safety subsystem — kill switch, write kernel, and M5 effect controls."""

from webwire.safety.dedupe import DedupeStore
from webwire.safety.effect_ledger import (
    EffectLedger,
    EffectLedgerCorruptError,
    EffectLedgerError,
    EffectLedgerRecord,
    EffectState,
    RecoveryProjection,
)
from webwire.safety.effect_policy import (
    DEFAULT_EFFECT_POLICIES,
    DurabilityPolicy,
    EffectPolicy,
    EffectPolicyRegistry,
    EffectVerb,
    PreparationVerb,
    ReplaySemantics,
    derive_durability,
)
from webwire.safety.kill_switch import KillSwitch
from webwire.safety.models import (
    Amplification,
    CompensationMeta,
    ConfirmationToken,
    PolicyDecision,
    PolicyVerdict,
    Reversibility,
    RiskMeta,
    RiskTier,
    Visibility,
    WriteIntent,
)
from webwire.safety.risk_registry import DEFAULT_REGISTRY, RiskRegistry
from webwire.safety.scoped_authority import (
    ClearBookmarkAuthority,
    ClearLikeAuthority,
    DeletePostAuthority,
    PostPreparationAuthority,
    QuotePreparationAuthority,
    ReplyPreparationAuthority,
    ScopedAuthorityBroker,
    ScopedAuthorityDenied,
    SetBookmarkAuthority,
    SetLikeAuthority,
    SubmitContentAuthority,
)
from webwire.safety.token_bucket import DEFAULT_LIMITS, BucketLimits, TokenBucket
from webwire.safety.write_kernel import PreviewResult, WriteCapability, WriteKernel

__all__ = [
    "KillSwitch",
    "WriteKernel",
    "WriteCapability",
    "PreviewResult",
    "WriteIntent",
    "RiskMeta",
    "RiskTier",
    "RiskRegistry",
    "DEFAULT_REGISTRY",
    "TokenBucket",
    "BucketLimits",
    "DEFAULT_LIMITS",
    "DedupeStore",
    "CompensationMeta",
    "ConfirmationToken",
    "PolicyDecision",
    "PolicyVerdict",
    "Visibility",
    "Reversibility",
    "Amplification",
    "EffectPolicy",
    "EffectPolicyRegistry",
    "DEFAULT_EFFECT_POLICIES",
    "EffectVerb",
    "PreparationVerb",
    "ReplaySemantics",
    "DurabilityPolicy",
    "derive_durability",
    "EffectLedger",
    "EffectLedgerRecord",
    "EffectLedgerError",
    "EffectLedgerCorruptError",
    "EffectState",
    "RecoveryProjection",
    "ScopedAuthorityBroker",
    "ScopedAuthorityDenied",
    "PostPreparationAuthority",
    "ReplyPreparationAuthority",
    "QuotePreparationAuthority",
    "SetBookmarkAuthority",
    "ClearBookmarkAuthority",
    "SetLikeAuthority",
    "ClearLikeAuthority",
    "DeletePostAuthority",
    "SubmitContentAuthority",
]
